# Generated by Django 4.1.7 on 2023-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='course',
            field=models.ManyToManyField(blank=True, to='course_api.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, to='course_api.course'),
        ),
    ]
