# Generated by Django 4.1.7 on 2023-03-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_logbox_delete_bag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAssets',
        ),
    ]
