# Generated by Django 4.1.7 on 2023-03-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_delete_imageassets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbox',
            options={'verbose_name_plural': 'Log Boxes'},
        ),
        migrations.AlterField(
            model_name='logbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
