# Generated by Django 4.1.7 on 2023-02-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0002_manager_course_teacher_course'),
        ('scheme_api', '0002_rename_scheme_scheme_topic'),
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_num', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration allowed for Quiz in minutes')),
                ('level', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('difficult', 'difficult')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme_api.scheme')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.teacher')),
            ],
            options={
                'verbose_name_plural': 'quizes',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('time_taken', models.IntegerField(default=10)),
                ('time_completed', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('set_on', models.DateTimeField(auto_now_add=True, help_text='when question was first set')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='when answer was first added')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.question')),
            ],
        ),
    ]
