# Generated by Django 4.1.7 on 2023-02-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_remove_quiz_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='scheme',
            new_name='topic',
        ),
    ]
