# Generated by Django 4.1.7 on 2023-03-24 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_rename_scheme_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
