# Generated by Django 4.1.7 on 2023-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0006_score_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_num',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
