# Generated by Django 4.1.7 on 2023-02-25 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=30)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('video', models.FileField(default='vid.jpg', upload_to='TM/Scheme_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme_api.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=10000)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme_api.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='TM/Scheme_images')),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme_api.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doc', models.FileField(upload_to='TM/Scheme_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme_api.scheme')),
            ],
        ),
    ]
