# Generated by Django 4.1.7 on 2023-02-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='scheme',
            new_name='topic',
        ),
    ]
