# Generated by Django 4.1.7 on 2023-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_api', '0002_rename_scheme_scheme_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='image_box')),
            ],
        ),
    ]
