# Generated by Django 4.1.7 on 2023-03-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_api', '0005_remove_image_image_url_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
